In [1]:
import re
import os
import nltk
import pandas as pd
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer, WordNetLemmatizer
import string
from collections import defaultdict

In [2]:
def normalize_text(text):
    text = text.lower()
    #text = re.sub(r'[^\w\s]', '', text)
    text = re.sub(r'[^a-zA-Z\s]', '', text)
    text = re.sub(r'\s+', ' ', text).strip()
    return text

In [3]:
#REad the stop words list
stop_words_paht='data/reuters/stopwords'
stop_words=[]
with open(stop_words_paht,'r') as file:
    content=file.read().split('\n')
    stop_words.append(content)
    

In [4]:
stemmer = PorterStemmer()
lemmatizer = WordNetLemmatizer()

In [5]:
data_directory = 'data/reuters/training/'
filenames=os.listdir(data_directory)
filenames.sort(key=lambda x: int(x))


In [48]:
data_directory = 'data/reuters/training/'
word_counts = defaultdict(int)
wset = set()
nltk.download('stopwords')
stop_words2 = set(stopwords.words('english'))
stem_docs = {}
real_doc={}

def load_data():
    for filename in filenames:
        with open(os.path.join(data_directory, filename), 'r') as file:
            content = file.read()
            real_doc[filename]=content
            content = normalize_text(content)
            sdoc = []
            for word in content.lower().translate(str.maketrans('', '', string.punctuation)).split(" "):
                if word not in stop_words[0] or word not in stop_words2:
                    word = lemmatizer.lemmatize(word)
                    wset.add(word)
                    word_counts[word] += 1
                    sdoc.append(word) 
            sdoc_concatenated = ' '.join(sdoc)
            # Añadir el documento procesado al diccionario stem_docs
            stem_docs[filename] = sdoc_concatenated  
                                                 

[nltk_data] Downloading package stopwords to
[nltk_data]     /home/jeffersonc/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [7]:
load_data()

In [10]:
i=0
for filename, content in stem_docs.items():
    print(f"Nombre del archivo: {filename}")
    print(f"Contenido del archivo: {content}\n")
    if(i>=5):
       break
    else:
        i+=1

Nombre del archivo: 1
Contenido del archivo: ['bahia', 'cocoa', 'review', 'shower', 'continued', 'throughout', 'week', 'bahia', 'cocoa', 'zone', 'alleviating', 'drought', 'since', 'early', 'january', 'improving', 'prospect', 'coming', 'temporao', 'although', 'normal', 'humidity', 'level', 'restored', 'comissaria', 'smith', 'said', 'weekly', 'review', 'dry', 'period', 'mean', 'temporao', 'late', 'year', 'arrival', 'week', 'ended', 'february', 'bag', 'kilo', 'making', 'cumulative', 'total', 'season', 'mln', 'stage', 'last', 'year', 'seems', 'cocoa', 'delivered', 'earlier', 'consignment', 'included', 'arrival', 'figure', 'comissaria', 'smith', 'said', 'still', 'doubt', 'much', 'old', 'crop', 'cocoa', 'still', 'available', 'harvesting', 'practically', 'come', 'end', 'total', 'bahia', 'crop', 'estimate', 'around', 'mln', 'bag', 'sale', 'standing', 'almost', 'mln', 'hundred', 'thousand', 'bag', 'still', 'hand', 'farmer', 'middleman', 'exporter', 'processor', 'doubt', 'much', 'cocoa', 'would'

In [8]:
import pandas as pd

unique_words = set()

files_content=stem_docs
for file_content in files_content.values():
    unique_words.update(file_content)

df = pd.DataFrame(0, index=files_content.keys(), columns=sorted(unique_words))

for file_name, file_content in files_content.items():
    for word in file_content:
        df.at[file_name, word] += 1


In [9]:
df

aa  aaa  aachener  aaminus  aancor  aap  aaplus  aaps  aar  aarnoud  \
1       0    0         0        0       0    0       0     0    0        0   
5       0    0         0        0       0    0       0     0    0        0   
6       0    0         0        0       0    0       0     0    0        0   
9       0    0         0        0       0    0       0     0    0        0   
10      0    0         0        0       0    0       0     0    0        0   
...    ..  ...       ...      ...     ...  ...     ...   ...  ...      ...   
14779   0    0         0        0       0    0       0     0    0        0   
14783   0    0         0        0       0    0       0     0    0        0   
14785   0    0         0        0       0    0       0     0    0        0   
14805   0    0         0        0       0    0       0     0    0        0   
14818   0    0         0        0       0    0       0     0    0        0   

       ...  zorinsky  zseven  zuccherifici  zuckerman  zulia  zurich  \
1      ...         0       0             0          0      0       0   
5      ...         0       0             0          0      0       0   
6      ...         0       0             0          0      0       0   
9      ...         0       0             0          0      0       0   
10     ...         0       0             0          0      0       0   
...    ...       ...     ...           ...        ...    ...     ...   
14779  ...         0       0             0          0      0       0   
14783  ...         0       0             0          0      0       0   
14785  ...         0       0             0          0      0       0   
14805  ...         0       0             0          0      0       0   
14818  ...         0       0             0          0      0       0   

       zurichbased  zuyuan  zverev  zzzz  
1                0       0       0     0  
5                0       0       0     0  
6                0       0       0     0  
9                0       0       0     0  
10               0       0       0     0  
...            ...     ...     ...   ...  
14779            0       0       0     0  
14783            0       0       0     0  
14785            0       0       0     0  
14805            0       0       0     0  
14818            0       0       0     0  

[7769 rows x 26376 columns]

In [13]:
# Filtrar las columnas donde el valor es igual a 1 en la fila especificada
columnas_con_uno = df.columns[df.iloc[0] == 1]

# Imprimir las columnas que tienen el valor de 1
print("Columnas con valor 1 en la fila", 0, ":")
print(columnas_con_uno)


Columnas con valor 1 en la fila 0 :
Index(['alleviating', 'almost', 'also', 'although', 'aprilmay', 'argentina',
       'around', 'arroba', 'aug', 'available', 'booked', 'brazilian', 'buyer',
       'cake', 'carnival', 'certificate', 'come', 'coming', 'commission',
       'continued', 'convertible', 'covertible', 'cruzados', 'cumulative',
       'currently', 'delivered', 'destination', 'dificulties', 'drought',
       'dry', 'earlier', 'early', 'ended', 'estimate', 'estimated', 'expected',
       'experiencing', 'export', 'exporter', 'final', 'fit', 'fob', 'going',
       'good', 'hand', 'harvesting', 'held', 'humidity', 'hundred',
       'improving', 'included', 'january', 'last', 'late', 'level', 'light',
       'liquor', 'lower', 'made', 'making', 'march', 'mean', 'midday',
       'middleman', 'named', 'nearby', 'normal', 'obtaining', 'offer', 'old',
       'part', 'practically', 'price', 'processor', 'prospect', 'published',
       'quality', 'recent', 'registered', 'reluctant', 'r

In [14]:
df.to_csv('Back_of_words_version2.1.csv', index=True)

Similitud Jaccard

In [10]:
nombres_columnas = df.columns.tolist()

In [31]:
def crear_array_regex(query, nombres_columnas):
    patrones = [r'\b{}\b'.format(re.escape(palabra)) for palabra in query.split()]
    regex = re.compile('|'.join(patrones))
    resultado = [1 if regex.search(columna) else 0 for columna in nombres_columnas]
    
    return resultado

query = "rubber"
array_resultado = crear_array_regex(query, nombres_columnas)

In [32]:
for valie in array_resultado:
    if valie==1:
        print(valie)

1


In [33]:
titulos = df.index.tolist()


In [34]:
import numpy as np
    
def similitud_jaccard(query, text, scores):
    # Calcular la intersección
    interseccion = np.sum(np.logical_and(query, text))

    # Calcular la unión
    union = np.sum(np.logical_or(query, text))

    # Calcular la similitud Jaccard
    jaccard_score = interseccion / union if union != 0 else 0.0

    # Agregar el score calculado a la lista `scores`
    scores.append(jaccard_score)

In [35]:
def ranked_skores_jaccard(scores):
    score_sorted=sorted(scores,reverse=True)
    #best_scores=score_sorted[:3]
    best_titles = []
    titulos_aux=titulos.copy()
    contador=0
    for score in score_sorted:
        if score>0:
            indice = scores.index(score) 
            best_titles.append(titulos[indice])     
            scores[indice]=None
            titulos_aux[indice]=None   
    return best_titles

In [36]:
array_query = np.array(array_resultado)
print("Query a procesar: ",query)
scores_jaccard=[]
for ind,fil in df.iterrows():
    array_doc=np.array(fil)
    similitud_jaccard(array_query,array_doc,scores_jaccard)
best_titles=ranked_skores_jaccard(scores_jaccard)


Query a procesar:  rubber


In [37]:
for i,best_file in enumerate(best_titles):
    print("Mejor titulo: ", best_file,"\n",real_doc[best_file])
    if i>5:
        break
    

Mejor titulo:  7860 
 U.N. Conference formally adopts new International Natural Rubber Agreement - chairman

  U.N. Conference formally adopts new International Natural Rubber Agreement - chairman
  


Mejor titulo:  5138 
 GENEVA - negotiators at U.N. Conference agree basic elements in new rubber pact - chairman

  GENEVA - negotiators at U.N. Conference agree basic elements in new rubber pact - chairman
  


Mejor titulo:  14783 
 JAPAN RUBBER STOCKS FALL IN MARCH
  Japan's rubber stocks fell to 44,980
  tonnes in March from 46,198 in February and from 53,784 in
  March 1986, the Japan Rubber Trade Association said.
      The stocks (in tonnes), with February and year-earlier
  comparisons, were -
                      March 87  Feb 87    March 86
      Crude Rubber     41,536   42,094     49,551
      Synthetic         3,334    3,978      4,044
      Latex               110      126        189
  


Mejor titulo:  884 
 MALAYSIA RE-IMPOSES EXPORT DUTIES ON RUBBER
  The Malaysian gove

In [39]:
# Filtrar las filas donde 'trade' y 'example' son ambos iguales a 1
filas_con_uno = df[(df['rubber'] == 1)] #& (df['example'] == 1)]

# Seleccionar solo las columnas 'trade' y 'example' de las filas filtradas
#resultado = filas_con_uno[['trade', 'example']]
resultado=filas_con_uno[['rubber']]

# Mostrar el resultado
print("Filas donde 'trade' y 'example' tienen valor de 1:")
resultado

Filas donde 'trade' y 'example' tienen valor de 1:


rubber
820         1
1292        1
1572        1
2476        1
3596        1
3707        1
5258        1
5533        1
6665        1
6752        1
6954        1
8603        1
8914        1
9153        1
9769        1
10674       1
10693       1
11201       1
11504       1
12959       1
13958       1

Coseno


In [26]:
def calculo_distancia(np_array_query, np_array_text,scores):
  producto_punto = np.dot(np_array_query, np_array_text)

  norma_a = np.linalg.norm(np_array_query)
  norma_b = np.linalg.norm(np_array_text)

  distancia_coseno = producto_punto / (norma_a * norma_b)
  scores.append(distancia_coseno)

In [27]:
def ranked_skores(scores):
    score_sorted=sorted(scores,reverse=True)
    #best_scores=score_sorted[:3]
    best_titles = []
    titulos_aux=titulos.copy()
    contador=0
    for score in score_sorted:
        if score>0:       
            indice = scores.index(score) 
            best_titles.append(titulos[indice])     
            scores[indice]=None
            titulos_aux[indice]=None 
    return best_titles

In [28]:
import numpy as np
array_query = np.array(array_resultado)
print("Query a procesar: ",query)
scores=[]
for ind,fil in df.iterrows():
    array_doc=np.array(fil)
    calculo_distancia(array_query,array_doc,scores)
best_titles=ranked_skores(scores)


Query a procesar:  trade and example


In [29]:
for i,best_file in enumerate(best_titles):
    print("Mejor titulo: ", best_file,"\n",real_doc[best_file])
    if i>5:
        break
    

Mejor titulo:  9315 
 KEY U.S. HOUSE PANEL FINISHES MAJOR TRADE BILL
  The House Ways and Means Committee
  completed action on legislation to toughen U.S. trade laws,
  chairman Dan Rostenkowski said.
      The committee's consideration of one of the most
  controversial provisions, a plan to force major trade surplus
  countries to cut their trade imbalance with the United States,
  was deferred until the full House considers the trade bill, its
  sponsor Rep. Richard Gephardt said.
      Gephardt, a Missouri Democrat, told Reuters he was not
  certain the exact form his trade surplus reduction proposal
  would take. Last year the House approved his plan to force a 10
  pct surplus cutback each year for four years, by countries such
  as Japan.
      The Ways and Means Committess' trade bill forces President
  Reagan to retaliate against unfair trade practices that violate
  international trade agreements but it allows him to wave
  retaliatory tariffs or quotas if the action would h

TF-IDF


# Aplicar Bag of Words (BoW) bow_matrix = count_vectorizer.fit_transform(df['document']) bow_feature_names = count_vectorizer.get_feature_names_out() # Aplicar TF-IDF tfidf_matrix = tfidf_vectorizer.fit_transform(df['document']) tfidf_feature_names = tfidf_vectorizer.get_feature_names_out(

In [49]:
load_data()

In [50]:
filenames = list(real_doc.keys())
documents = list(real_doc.values())
stemmed_documents = [stem_docs[filename] for filename in filenames]

# Crear el DataFrame
df2 = pd.DataFrame({
    'filename': filenames,
    'original_document': documents,
    'stemmed_document': stemmed_documents
})

In [51]:
df2

filename                                  original_document  \
0           1  BAHIA COCOA REVIEW\n  Showers continued throug...   
1           5  NATIONAL AVERAGE PRICES FOR FARMER-OWNED RESER...   
2           6  ARGENTINE 1986/87 GRAIN/OILSEED REGISTRATIONS\...   
3           9  CHAMPION PRODUCTS &lt;CH> APPROVES STOCK SPLIT...   
4          10  COMPUTER TERMINAL SYSTEMS &lt;CPML> COMPLETES ...   
...       ...                                                ...   
7764    14779  BANK OF JAPAN INTERVENES SOON AFTER TOKYO OPEN...   
7765    14783  JAPAN RUBBER STOCKS FALL IN MARCH\n  Japan's r...   
7766    14785  SOUTH KOREAN WON FIXED AT 25-MONTH HIGH\n  THE...   
7767    14805  NIPPON MINING LOWERS COPPER PRICE\n  Nippon Mi...   
7768    14818  AUSTRALIAN UNIONS LAUNCH NEW SOUTH WALES STRIK...   

                                       stemmed_document  
0     bahia cocoa review shower continued throughout...  
1     national average price farmerowned reserve u a...  
2     argentine grainoilseed registration argentine ...  
3     champion product ltch approves stock split cha...  
4     computer terminal system ltcpml completes sale...  
...                                                 ...  
7764  bank japan intervenes soon tokyo opening bank ...  
7765  japan rubber stock fall march japan rubber sto...  
7766  south korean won fixed month high bank korea s...  
7767  nippon mining lower copper price nippon mining...  
7768  australian union launch new south wale strike ...  

[7769 rows x 3 columns]

In [61]:
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer

# Crear un objeto CountVectorizer
count_vectorizer = CountVectorizer()

# Aplicar fit_transform a la columna 'stemmed_document'
bow_matrix = count_vectorizer.fit_transform(df2['stemmed_document'])
bow_feature_names = count_vectorizer.get_feature_names_out()



In [58]:
print(len(bow_feature_names))
print(bow_matrix.toarray())

26357
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [63]:
tfidf_vectorizer = TfidfVectorizer()
tfidf_matrix = tfidf_vectorizer.fit_transform(df2['stemmed_document'])
tfidf_feature_names = tfidf_vectorizer.get_feature_names_out()

In [64]:
tfidf_matrix.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [ ]:
# Aplicar Bag of Words (BoW) 
bow_matrix = count_vectorizer.fit_transform(df['document'])
bow_feature_names = count_vectorizer.get_feature_names_out()
#Aplicar TF-IDF 
tfidf_matrix = tfidf_vectorizer.fit_transform(df['document']) tfidf_feature_names = tfidf_vectorizer.get_feature_names_out()